#!/usr/bin/env bash
set -euo pipefail

file="src/ui.js"
mod="src/module.json"

rg -q "import \{ shouldFilterMessage, decodeDelta \} from '../../shared/input_filter.mjs';" "$file"
rg -q "function noteToPad\(" "$file"
rg -q "const PAD_NOTE_MIN = 36;" "$file"
rg -q "const PAD_NOTE_MAX = 67;" "$file"
rg -q "const PAD_NOTE_FALLBACK_MIN = 68;" "$file"
rg -q "const PAD_NOTE_FALLBACK_MAX = 99;" "$file"
rg -q "const delta = decodeDelta\(d2\);" "$file"
rg -q "global_octave" "$file"
rg -q "global_transpose" "$file"
rg -q "pad_octave" "$file"
rg -q "const EDIT_KEYS   = \\['pad','pad_octave','root','chord_type','inversion','strum','strum_dir','articulation','reverse_art','global_octave','global_transpose','save'\\]" "$file"
rg -q "const isTranspose = key === 'global_transpose';" "$file"
rg -q "Global Trans" "$file"
rg -q "if \\(key === 'root'\\) return raw.toUpperCase\\(\\);" "$file"
rg -q "function triggerSave\(" "$file"
rg -q "dspSet\('save', 'save'\);" "$file"
rg -q "\"key\": \"global_octave\"" "$mod"
rg -q "\"key\": \"global_transpose\"" "$mod"
rg -q "\"key\": \"pad_octave\"" "$mod"
rg -q "\"key\": \"chord_type\"" "$mod"
rg -q "\"knobs\": \\[\"pad\",\"pad_octave\",\"root\",\"chord_type\",\"inversion\",\"strum\",\"global_octave\",\"global_transpose\"\\]" "$mod"
rg -q "\"key\": \"global_octave\".*\"min\": -6, \"max\": 6.*\"default\": 2" "$mod"
rg -q "\"key\": \"global_transpose\".*\"min\": -12, \"max\": 12.*\"default\": 0" "$mod"
rg -q "\"key\": \"pad_octave\".*\"min\": -6, \"max\": 6" "$mod"
